package projetechec;


import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.xml.transform.TransformerException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aaraby
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public static XML xml1 = new XML();
    public static XMLTournoi xml2 = new XMLTournoi();
    public MenuPrincipal() {
        initComponents();
        menuPrinc.setVisible(true);
        creationJoueur.setVisible(false);
        afficherJoueur.setVisible(false);
        creationTournoi.setVisible(false);
        remove(creationTournoi);
        remove(creationJoueur);
        remove(afficherJoueur);
        add(menuPrinc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrinc = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        createTournament = new javax.swing.JButton();
        createPlayer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        creationJoueur = new javax.swing.JPanel();
        nomLabel = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        sexeLabel = new javax.swing.JLabel();
        licenceLabel = new javax.swing.JLabel();
        federationLabel = new javax.swing.JLabel();
        ligueLabel = new javax.swing.JLabel();
        clubLabel = new javax.swing.JLabel();
        eloNormalLabel = new javax.swing.JLabel();
        eloRapideLabel = new javax.swing.JLabel();
        eloSemiRapideLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        nomTextField = new javax.swing.JTextField();
        mainMenuButton = new javax.swing.JButton();
        prenomTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        licenceTextField = new javax.swing.JTextField();
        federationTextField = new javax.swing.JTextField();
        ligueTextField = new javax.swing.JTextField();
        clubTextField = new javax.swing.JTextField();
        eloNormalTextField = new javax.swing.JTextField();
        eloSemiRapideTextField = new javax.swing.JTextField();
        eloRapideTextField = new javax.swing.JTextField();
        noteLabel = new javax.swing.JLabel();
        titleMenuLabel = new javax.swing.JLabel();
        dateFormatLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        retourTextArea = new javax.swing.JTextArea();
        afficherJoueur = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AffJTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnafficherJ = new javax.swing.JButton();
        retourMenuAff = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        affichageJoueurList = new javax.swing.JList<>();
        supprimerJoueurButton = new javax.swing.JButton();
        modifierJoueurButton = new javax.swing.JButton();
        creationTournoi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        dated = new javax.swing.JLabel();
        datef = new javax.swing.JLabel();
        nbr = new javax.swing.JLabel();
        lieu = new javax.swing.JLabel();
        nomTextField1 = new javax.swing.JTextField();
        datedTextField2 = new javax.swing.JTextField();
        dateFTextField3 = new javax.swing.JTextField();
        nbRTextField4 = new javax.swing.JTextField();
        lieuTextField5 = new javax.swing.JTextField();
        dateFormatLabel2 = new javax.swing.JLabel();
        dateFormatLabel3 = new javax.swing.JLabel();
        enregistreT = new javax.swing.JButton();
        menuprincT = new javax.swing.JButton();
        cleanT = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        msgErreurT = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setSize(new java.awt.Dimension(800, 800));

        menuPrinc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPrinc.setMaximumSize(new java.awt.Dimension(800, 800));
        menuPrinc.setMinimumSize(new java.awt.Dimension(800, 800));
        menuPrinc.setName(""); // NOI18N
        menuPrinc.setPreferredSize(new java.awt.Dimension(800, 800));

        jLabel2.setText("Veuillez sélectionner un sous menu");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("Menu Principal");

        createTournament.setText("Création d'un tournoi");
        createTournament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTournamentActionPerformed(evt);
            }
        });

        createPlayer.setText("Création d'un joueur");
        createPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlayerActionPerformed(evt);
            }
        });

        jButton1.setText("Afficher les joueurs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPrincLayout = new javax.swing.GroupLayout(menuPrinc);
        menuPrinc.setLayout(menuPrincLayout);
        menuPrincLayout.setHorizontalGroup(
            menuPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincLayout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addGroup(menuPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(createPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTournament, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPrincLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );
        menuPrincLayout.setVerticalGroup(
            menuPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addComponent(createPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createTournament, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        getContentPane().add(menuPrinc, java.awt.BorderLayout.CENTER);

        creationJoueur.setMaximumSize(new java.awt.Dimension(800, 800));
        creationJoueur.setMinimumSize(new java.awt.Dimension(800, 800));

        nomLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomLabel.setText("Nom : *");

        prenomLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prenomLabel.setText("Prenom : *");

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateLabel.setText("Date de naissance : *");

        sexeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sexeLabel.setText("Sexe : *");

        licenceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        licenceLabel.setText("Numéro de licence :");

        federationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        federationLabel.setText("Fédération :");

        ligueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ligueLabel.setText("Ligue :");

        clubLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clubLabel.setText("Club :");

        eloNormalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eloNormalLabel.setText("Elo (Classique) :");

        eloRapideLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eloRapideLabel.setText("Elo (rapide) :");

        eloSemiRapideLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eloSemiRapideLabel.setText("Elo (Semi rapide) :");

        saveButton.setText("Sauvegarder");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        nomTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTextFieldActionPerformed(evt);
            }
        });

        mainMenuButton.setText("Menu Principal");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        federationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                federationTextFieldActionPerformed(evt);
            }
        });

        noteLabel.setFont(new java.awt.Font("Ubuntu", 3, 12)); // NOI18N
        noteLabel.setText("nb : (*) champs obligatoire");

        titleMenuLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titleMenuLabel.setText("Création d'une fiche joueur");

        dateFormatLabel.setFont(new java.awt.Font("Ubuntu", 2, 12)); // NOI18N
        dateFormatLabel.setText("JJ/MM/AAAA");

        clearButton.setText("Réinitialiser");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        retourTextArea.setColumns(20);
        retourTextArea.setRows(5);
        jScrollPane3.setViewportView(retourTextArea);

        javax.swing.GroupLayout creationJoueurLayout = new javax.swing.GroupLayout(creationJoueur);
        creationJoueur.setLayout(creationJoueurLayout);
        creationJoueurLayout.setHorizontalGroup(
            creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creationJoueurLayout.createSequentialGroup()
                .addContainerGap(998, Short.MAX_VALUE)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creationJoueurLayout.createSequentialGroup()
                        .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noteLabel)
                            .addGroup(creationJoueurLayout.createSequentialGroup()
                                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eloSemiRapideLabel)
                                    .addComponent(eloNormalLabel)
                                    .addComponent(clubLabel)
                                    .addComponent(ligueLabel)
                                    .addComponent(federationLabel)
                                    .addComponent(licenceLabel)
                                    .addComponent(dateLabel)
                                    .addComponent(prenomLabel)
                                    .addComponent(nomLabel)
                                    .addComponent(eloRapideLabel)
                                    .addComponent(sexeLabel))
                                .addGap(48, 48, 48)
                                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(creationJoueurLayout.createSequentialGroup()
                                        .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateFormatLabel))
                                    .addComponent(licenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(federationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ligueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clubTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eloNormalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eloSemiRapideTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eloRapideTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, creationJoueurLayout.createSequentialGroup()
                                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creationJoueurLayout.createSequentialGroup()
                        .addComponent(titleMenuLabel)
                        .addGap(319, 319, 319))))
        );
        creationJoueurLayout.setVerticalGroup(
            creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creationJoueurLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleMenuLabel)
                .addGap(26, 26, 26)
                .addComponent(noteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomLabel)
                    .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomLabel)
                    .addComponent(prenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFormatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexeLabel)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenceLabel)
                    .addComponent(licenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(federationLabel)
                    .addComponent(federationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ligueLabel)
                    .addComponent(ligueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clubLabel)
                    .addComponent(clubTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eloNormalLabel)
                    .addComponent(eloNormalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eloSemiRapideLabel)
                    .addComponent(eloSemiRapideTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eloRapideLabel)
                    .addComponent(eloRapideTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creationJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        getContentPane().add(creationJoueur, java.awt.BorderLayout.PAGE_START);

        afficherJoueur.setMaximumSize(new java.awt.Dimension(800, 800));
        afficherJoueur.setMinimumSize(new java.awt.Dimension(800, 800));
        afficherJoueur.setRequestFocusEnabled(false);

        AffJTextArea1.setColumns(20);
        AffJTextArea1.setRows(5);
        jScrollPane1.setViewportView(AffJTextArea1);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Affichage des joueurs");

        btnafficherJ.setText("Afficher");
        btnafficherJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnafficherJActionPerformed(evt);
            }
        });

        retourMenuAff.setText("Retour menu principal");
        retourMenuAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourMenuAffActionPerformed(evt);
            }
        });

        jScrollPane2.setAutoscrolls(true);

        affichageJoueurList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                affichageJoueurListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(affichageJoueurList);

        supprimerJoueurButton.setText("Supprimer Joueur");
        supprimerJoueurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerJoueurButtonActionPerformed(evt);
            }
        });

        modifierJoueurButton.setText("Modifier Joueur");
        modifierJoueurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierJoueurButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout afficherJoueurLayout = new javax.swing.GroupLayout(afficherJoueur);
        afficherJoueur.setLayout(afficherJoueurLayout);
        afficherJoueurLayout.setHorizontalGroup(
            afficherJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afficherJoueurLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(afficherJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(afficherJoueurLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(afficherJoueurLayout.createSequentialGroup()
                        .addComponent(btnafficherJ, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(modifierJoueurButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(supprimerJoueurButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(retourMenuAff, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(435, Short.MAX_VALUE))
        );
        afficherJoueurLayout.setVerticalGroup(
            afficherJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afficherJoueurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(afficherJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(afficherJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnafficherJ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifierJoueurButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retourMenuAff, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supprimerJoueurButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(374, Short.MAX_VALUE))
        );

        getContentPane().add(afficherJoueur, java.awt.BorderLayout.PAGE_END);

        creationTournoi.setMaximumSize(new java.awt.Dimension(800, 800));
        creationTournoi.setMinimumSize(new java.awt.Dimension(800, 800));
        creationTournoi.setPreferredSize(new java.awt.Dimension(800, 800));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setText("Création d'un tournoi");

        nom.setText("Nom : *");

        dated.setText("Date debut : *");

        datef.setText("Date fin : *");

        nbr.setText("Nombre de rondes : *");

        lieu.setText("Lieu :");

        nomTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTextField1ActionPerformed(evt);
            }
        });

        dateFTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFTextField3ActionPerformed(evt);
            }
        });

        lieuTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lieuTextField5ActionPerformed(evt);
            }
        });

        dateFormatLabel2.setFont(new java.awt.Font("Ubuntu", 2, 12)); // NOI18N
        dateFormatLabel2.setText("JJ/MM/AAAA");

        dateFormatLabel3.setFont(new java.awt.Font("Ubuntu", 2, 12)); // NOI18N
        dateFormatLabel3.setText("JJ/MM/AAAA");

        enregistreT.setText("Sauvegarder");
        enregistreT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistreTActionPerformed(evt);
            }
        });

        menuprincT.setText("Menu principal");
        menuprincT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuprincTActionPerformed(evt);
            }
        });

        cleanT.setText("Réinitialiser");
        cleanT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanTActionPerformed(evt);
            }
        });

        msgErreurT.setColumns(20);
        msgErreurT.setRows(5);
        jScrollPane4.setViewportView(msgErreurT);

        javax.swing.GroupLayout creationTournoiLayout = new javax.swing.GroupLayout(creationTournoi);
        creationTournoi.setLayout(creationTournoiLayout);
        creationTournoiLayout.setHorizontalGroup(
            creationTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creationTournoiLayout.createSequentialGroup()
                .addGroup(creationTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creationTournoiLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel4))
                    .addGroup(creationTournoiLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(creationTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(creationTournoiLayout.createSequentialGroup()
                                .addComponent(cleanT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enregistreT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuprincT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(creationTournoiLayout.createSequentialGroup()
                                .addGroup(creationTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nom)
                                    .addComponent(dated)
                                    .addComponent(datef)
                                    .addComponent(nbr)
                                    .addComponent(lieu))
                                .addGap(14, 14, 14)
                                .addGroup(creationTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lieuTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nbRTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(creationTournoiLayout.createSequentialGroup()
                                        .addComponent(datedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateFormatLabel2))
                                    .addGroup(creationTournoiLayout.createSequentialGroup()
                                        .addComponent(dateFTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateFormatLabel3)))))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        creationTournoiLayout.setVerticalGroup(
            creationTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creationTournoiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(creationTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nom)
                    .addComponent(nomTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(creationTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dated)
                    .addComponent(datedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFormatLabel2))
                .addGap(18, 18, 18)
                .addGroup(creationTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateFTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFormatLabel3))
                .addGap(18, 18, 18)
                .addGroup(creationTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nbRTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbr))
                .addGap(21, 21, 21)
                .addGroup(creationTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lieu)
                    .addComponent(lieuTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(creationTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enregistreT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cleanT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuprincT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(389, 389, 389))
        );

        nomTextField1.getAccessibleContext().setAccessibleName("nomT");
        datedTextField2.getAccessibleContext().setAccessibleName("DateDT");
        dateFTextField3.getAccessibleContext().setAccessibleName("DateFinT");
        nbRTextField4.getAccessibleContext().setAccessibleName("nbRonde");
        lieuTextField5.getAccessibleContext().setAccessibleName("lieuT");

        getContentPane().add(creationTournoi, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlayerActionPerformed
        
        menuPrinc.setVisible(false);
        afficherJoueur.setVisible(false);
        creationTournoi.setVisible(false);
        remove(creationTournoi);
        remove(menuPrinc);
        remove(afficherJoueur);
        add(creationJoueur);
        creationJoueur.setVisible(true);
    }//GEN-LAST:event_createPlayerActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        nomTextField.setText("");
        prenomTextField.setText("");
        dateTextField.setText("");
        licenceTextField.setText("");
        federationTextField.setText("");
        ligueTextField.setText("");
        clubTextField.setText("");
        eloNormalTextField.setText("");
        eloSemiRapideTextField.setText("");
        eloRapideTextField.setText("");
        retourTextArea.setText("");
        nomLabel.setForeground(Color.black);
        prenomLabel.setForeground(Color.black);
        sexeLabel.setForeground(Color.black);
        dateLabel.setForeground(Color.black);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void btnafficherJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnafficherJActionPerformed
        ArrayList<Joueurs> listJ = xml1.ReadXML();
        DefaultListModel listM = new DefaultListModel();
        affichageJoueurList.setModel(listM);
        String tmp="";
        String tmpList = "";
        for (int i=0;i<listJ.size();i++){
            tmp=tmp+" Joueur n°"+(i+1)+System.getProperty("line.separator");
            tmpList =(i+1)+" Joueur n°"+(i+1)+listJ.get(i).getNomJ();
            listM.addElement(tmpList);
            tmp=tmp+listJ.get(i).JtoString()+System.getProperty("line.separator");

        }
        AffJTextArea1.setText(tmp);

    }//GEN-LAST:event_btnafficherJActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        creationJoueur.setVisible(false);
        menuPrinc.setVisible(false);
       
        creationTournoi.setVisible(false);
        remove(creationTournoi);
        remove(menuPrinc);
        remove(creationJoueur);
        add(afficherJoueur);
        afficherJoueur.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createTournamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTournamentActionPerformed
        creationJoueur.setVisible(false);
        menuPrinc.setVisible(false);
        afficherJoueur.setVisible(false);
        remove(afficherJoueur);
        remove(menuPrinc);
        remove(creationJoueur);
        add(creationTournoi);
        creationTournoi.setVisible(true);
    }//GEN-LAST:event_createTournamentActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
       nomTextField.setText("");
        prenomTextField.setText("");
        dateTextField.setText("");
        licenceTextField.setText("");
        federationTextField.setText("");
        ligueTextField.setText("");
        clubTextField.setText("");
        eloNormalTextField.setText("");
        eloSemiRapideTextField.setText("");
        eloRapideTextField.setText("");
        retourTextArea.setText("");
        nomLabel.setForeground(Color.black);
        prenomLabel.setForeground(Color.black);
        sexeLabel.setForeground(Color.black);
        dateLabel.setForeground(Color.black);
        menuPrinc.setVisible(true);
        creationJoueur.setVisible(false);
        afficherJoueur.setVisible(false);
        creationTournoi.setVisible(false);
        remove(creationTournoi);
        remove(creationJoueur);
        remove(afficherJoueur);
        add(menuPrinc);
        menuPrinc.setVisible(true);
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void retourMenuAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourMenuAffActionPerformed

        creationJoueur.setVisible(false);
        afficherJoueur.setVisible(false);
        creationTournoi.setVisible(false);
        remove(creationTournoi);
        remove(creationJoueur);
        remove(afficherJoueur);
        add(menuPrinc);
        menuPrinc.setVisible(true);
        
    }//GEN-LAST:event_retourMenuAffActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String nom = nomTextField.getText(); //Vérification des champs qui ne peuvent pas être nuls
        String prenom = prenomTextField.getText();
        String dateDeNaissance = dateTextField.getText();
        String sexe = jComboBox1.getSelectedItem().toString();
        String licence = licenceTextField.getText();
        String eloN = eloNormalTextField.getText();
        String eloR = eloRapideTextField.getText();
        String eloSR = eloSemiRapideTextField.getText();
        String fed = federationTextField .getText();
        String lig = ligueTextField.getText();
        String clb = clubTextField.getText();
        nomLabel.setForeground(Color.black);
        prenomLabel.setForeground(Color.black);
        sexeLabel.setForeground(Color.black);
        dateLabel.setForeground(Color.black);
        
        Joueurs j = new Joueurs(licence,nom,prenom,eloN,eloSR,eloR,dateDeNaissance,sexe,fed,lig,clb);
        String stmp="Données incorrectes: ";
        boolean test = true;
        if(!j.verifDonneeEnregistrementJoueur())
        {
            test= false;
            if(j.nomEstVide()){
                nomLabel.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Nom Joueur manquant";
            } 
            if(j.prenomEstVide()){
                prenomLabel.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Prénom Joueur manquant";
            }
            if(j.sexeEstVide()){
                sexeLabel.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Sexe Joueur manquant";
            }
            if(j.dateEstVide()){
                nbr.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Date de naissance manquante";
            }
        }else{
            if(!j.verifFormatNomValide()){
                test= false;
                nomLabel.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Nom Joueur invalide";
            }
            if(!j.verifFormatPrenomValide()){
                test= false;
                prenomLabel.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Prénom Joueur invalide";
            }
        }
        
        if(!j.verifTailleNomJoueur()){
            nomLabel.setForeground(Color.red);
            stmp += System.getProperty("line.separator")+"Nom de joueur limité à 50 caractères.";
        }
        
        if(!j.verifTaillePrenomJoueur()){
            prenomLabel.setForeground(Color.red);
            stmp += System.getProperty("line.separator")+"Prénom de joueur limité à 50 caractères.";
        }
        
        if(!j.verifNumLicenceValide()){
            test = false;
            stmp += System.getProperty("line.separator")+"Erreur, Format de licence incorrecte, format attendu : A12345";
        }
        
        if(!j.verifFormatDateValide(dateDeNaissance))
        {
            test = false;
            if(!j.verifMatchDate(dateDeNaissance)){
                dateLabel.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Erreur, date invalide format attendu : JJ/MM/AAAA";
            }
            if(!j.verifDateValide(dateDeNaissance)){
                dateLabel.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Erreur, date incorrecte";
            }
        } 
        if(j.verifFormatDateValide(dateDeNaissance)){
            if(!j.verifDateNaiss(dateDeNaissance)){
                test= false;
                dateLabel.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Erreur, date de naissance supérieure à la date actuelle.";
            }
        }
        
        if(!j.verifFormatEloValide(eloN)){
            test= false;
            stmp += System.getProperty("line.separator")+"Erreur, Elo Classique invalide.";
        }
        
        if(!j.verifFormatEloPositif(eloN)){
            test= false;
            stmp += System.getProperty("line.separator")+"Erreur, Elo Classique négatif.";
        }
        
        if(!j.verifFormatElo900To3000(eloN)){
            test= false;
            stmp += System.getProperty("line.separator")+"Erreur, Elo Classique doit être compris entre 900 et 3000.";
        }
        
        if(!j.verifFormatEloValide(eloR)){
            test= false;
            stmp += System.getProperty("line.separator")+"Erreur, Elo Rapide invalide.";
        }
        
        if(!j.verifFormatEloPositif(eloR)){
            test= false;
            stmp += System.getProperty("line.separator")+"Erreur, Elo Rapide négatif.";
        }
        
        if(!j.verifFormatElo900To3000(eloR)){
            test= false;
            stmp += System.getProperty("line.separator")+"Erreur, Elo Rapide doit être compris entre 900 et 3000.";
        }
        
        if(!j.verifFormatEloValide(eloSR)){
            test= false;
            stmp += System.getProperty("line.separator")+"Erreur, Elo SemiRapide invalide.";
        }
        
        if(!j.verifFormatEloPositif(eloSR)){
            test= false;
            stmp += System.getProperty("line.separator")+"Erreur, Elo SemiRapide négatif.";
        }
        
        if(!j.verifFormatElo900To3000(eloSR)){
            test= false;
            stmp += System.getProperty("line.separator")+"Erreur, Elo SemiRapide doit être compris entre 900 et 3000.";
        }
        
        if(!j.verifFormatLigueValide()){
            test= false;
            stmp += System.getProperty("line.separator")+"Erreur, ligue invalide.";
        }
        
        if(!j.verifFormatFedValide()){
            test= false;
            stmp += System.getProperty("line.separator")+"Erreur, Federation invalide.";
        }
                
        retourTextArea.setText(stmp);
        if(test){
            retourTextArea.setText("Joueur créé avec succès !");
            xml1.WriteXML(j);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cleanTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanTActionPerformed
        nomTextField1.setText("");
        datedTextField2.setText("");
        dateFTextField3.setText("");
        nbRTextField4.setText("");
        lieuTextField5.setText("");
        msgErreurT.setText("");
        nom.setForeground(Color.black);
        dated.setForeground(Color.black);
        datef.setForeground(Color.black);
        nbr.setForeground(Color.black);
    }//GEN-LAST:event_cleanTActionPerformed

    private void menuprincTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuprincTActionPerformed
        nomTextField1.setText("");
        datedTextField2.setText("");
        dateFTextField3.setText("");
        nbRTextField4.setText("");
        lieuTextField5.setText("");
        msgErreurT.setText("");
        nom.setForeground(Color.black);
        dated.setForeground(Color.black);
        datef.setForeground(Color.black);
        nbr.setForeground(Color.black);
        creationJoueur.setVisible(false);
        afficherJoueur.setVisible(false);
        creationTournoi.setVisible(false);
        remove(creationTournoi);
        remove(creationJoueur);
        remove(afficherJoueur);
        add(menuPrinc);
        menuPrinc.setVisible(true);
    }//GEN-LAST:event_menuprincTActionPerformed

    private void enregistreTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistreTActionPerformed
        String nomTournoi=nomTextField1.getText();
        String dateDebut= datedTextField2.getText();
        String dateFin=dateFTextField3.getText();
        String nbRondes=nbRTextField4.getText();
        String lieu=lieuTextField5.getText();
        nom.setForeground(Color.black);
        dated.setForeground(Color.black);
        datef.setForeground(Color.black);
        nbr.setForeground(Color.black);
        Tournoi t = new Tournoi(nomTournoi,dateDebut,dateFin,nbRondes,lieu);
        String stmp="Données incorrectes: ";
        boolean test = true;
        if(!t.verifDonneesSensiblesCompletes())
        {
            test= false;
            if(t.nomTournoiEstVide()){
                nom.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Nom Tournoi manquant";
            }
            if(t.dateDebutEstVide()){
                dated.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Date de début manquante";
            }
            if(t.dateFinEstVide()){
                datef.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Date de fin manquante";
            }
            if(t.nbRondesEstVide()){
                nbr.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Nombre de rondes manquant";
            }
        }
        if(!t.verifTailleNomTournoi()){
            nom.setForeground(Color.red);
            stmp += System.getProperty("line.separator")+"Nom de tournoi limité à 50 caractères.";
        }
        if(!t.verifFormatDateValide(dateDebut))
        {
            test= false;
            if(!t.verifMatchDate(dateDebut)){
                dated.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Erreur, date invalide format attendu : JJ/MM/AAAA";
            }
            if(!t.verifDateValide(dateDebut)){
                dated.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Erreur, date incorrecte";
            }
        } 
        if(!t.verifFormatDateValide(dateFin))
        {
            test= false;
            if(!t.verifMatchDate(dateFin)){
                dated.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Erreur, date invalide format attendu : JJ/MM/AAAA";
            }
            if(!t.verifDateValide(dateFin)){
                dated.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Erreur, date incorrecte";
            }
        }
        if(t.verifFormatDateValide(dateDebut) && t.verifFormatDateValide(dateFin)){
            if(!t.verifDateDebut(dateDebut)){
                test= false;
                dated.setForeground(Color.red);
                stmp += System.getProperty("line.separator")+"Erreur, date de début inférieure à la date actuelle.";
            }
            if(!t.verifDateDebutAvantDateFin(dateDebut, dateFin)){
                test= false;
                stmp += System.getProperty("line.separator")+"Erreur, date de début plus récente que date de fin.";
            }
        }
        if(!t.verifNbRondes()){
            test = false;
            stmp += System.getProperty("line.separator")+"Erreur, le nombre de rondes doit être positif.";
        }
        msgErreurT.setText(stmp);
        if(test){
            msgErreurT.setText("Tournoi créé avec succès !");
            xml2.WriteXML(t);
        }
    }//GEN-LAST:event_enregistreTActionPerformed

    private void lieuTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lieuTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lieuTextField5ActionPerformed

    private void dateFTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFTextField3ActionPerformed

    private void nomTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTextField1ActionPerformed

    private void nomTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void federationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_federationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_federationTextFieldActionPerformed

    private void affichageJoueurListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_affichageJoueurListValueChanged
        ArrayList<Joueurs> listJ = xml1.ReadXML();
        String afftmp;
        String s = (String) affichageJoueurList.getSelectedValue();
        String tmp = s.split(" ")[0];
        int intTmp = Integer.valueOf(tmp);
        afftmp=listJ.get(intTmp-1).JtoString()+System.getProperty("line.separator");
        AffJTextArea1.setText(afftmp);
    }//GEN-LAST:event_affichageJoueurListValueChanged

    private void supprimerJoueurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerJoueurButtonActionPerformed
        String s = (String) affichageJoueurList.getSelectedValue();
        int intTmp = Integer.valueOf(""+s.charAt(0));
        try {
            xml1.supprimerJoueur(intTmp-1);
        } catch (TransformerException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_supprimerJoueurButtonActionPerformed

    private void modifierJoueurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierJoueurButtonActionPerformed
        ArrayList<Joueurs> listJ = xml1.ReadXML();
        String s = (String) affichageJoueurList.getSelectedValue();
        int intTmp = Integer.valueOf(""+s.charAt(0));
        
        //Faut pas faire comme ça faut créer un nouveau pannel
        xml1.modifierJoueur(intTmp-1, listJ.get(intTmp-1));
    }//GEN-LAST:event_modifierJoueurButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AffJTextArea1;
    private javax.swing.JList<String> affichageJoueurList;
    private javax.swing.JPanel afficherJoueur;
    private javax.swing.JButton btnafficherJ;
    private javax.swing.JButton cleanT;
    private javax.swing.JToggleButton clearButton;
    private javax.swing.JLabel clubLabel;
    private javax.swing.JTextField clubTextField;
    private javax.swing.JButton createPlayer;
    private javax.swing.JButton createTournament;
    private javax.swing.JPanel creationJoueur;
    private javax.swing.JPanel creationTournoi;
    private javax.swing.JTextField dateFTextField3;
    private javax.swing.JLabel dateFormatLabel;
    private javax.swing.JLabel dateFormatLabel2;
    private javax.swing.JLabel dateFormatLabel3;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel dated;
    private javax.swing.JTextField datedTextField2;
    private javax.swing.JLabel datef;
    private javax.swing.JLabel eloNormalLabel;
    private javax.swing.JTextField eloNormalTextField;
    private javax.swing.JLabel eloRapideLabel;
    private javax.swing.JTextField eloRapideTextField;
    private javax.swing.JLabel eloSemiRapideLabel;
    private javax.swing.JTextField eloSemiRapideTextField;
    private javax.swing.JButton enregistreT;
    private javax.swing.JLabel federationLabel;
    private javax.swing.JTextField federationTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel licenceLabel;
    private javax.swing.JTextField licenceTextField;
    private javax.swing.JLabel lieu;
    private javax.swing.JTextField lieuTextField5;
    private javax.swing.JLabel ligueLabel;
    private javax.swing.JTextField ligueTextField;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JPanel menuPrinc;
    private javax.swing.JButton menuprincT;
    private javax.swing.JButton modifierJoueurButton;
    private javax.swing.JTextArea msgErreurT;
    private javax.swing.JTextField nbRTextField4;
    private javax.swing.JLabel nbr;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField nomTextField;
    private javax.swing.JTextField nomTextField1;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JTextField prenomTextField;
    private javax.swing.JButton retourMenuAff;
    private javax.swing.JTextArea retourTextArea;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sexeLabel;
    private javax.swing.JButton supprimerJoueurButton;
    private javax.swing.JLabel titleMenuLabel;
    // End of variables declaration//GEN-END:variables
}
